version: '3.8'

services:
  # Backend Flask uniquement
  # GraphDB doit tourner séparément sur ton Mac (localhost:7200)
  backend:
    build: .
    container_name: wlc-backend
    ports:
      - "8000:8000"
    environment:
      - GRAPHDB_URL=http://host.docker.internal:7200
      - GRAPHDB_REPO=wlconto
    volumes:
      - ./Backend/uploads:/app/uploads
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

