name: wlc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ifcopenshell
  - pip
  - pip:
    - Flask==3.0.2
    - Flask-CORS==4.0.0
    - pandas==1.5.3
    - requests==2.31.0
    - Werkzeug==3.0.1
    - openpyxl==3.1.2
    - python-dotenv==1.0.1
    - gunicorn==21.2.0

